# -*- coding: utf-8 -*-
"""CV Image Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LA9XhlOkuIwqcPASP6KZ5g9RpdcA1lkN

<h1><b><center>CV Image Classification</center></b></h1><hr>
"""

from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
from tensorflow.keras.applications.resnet50 import ResNet50
import numpy as np

# Load the model
model = ResNet50(weights='imagenet')

# Load the image
img_path = 'dog230.jpg'
img = image.load_img(img_path, target_size=(224, 224))

# Convert the image to a numpy array
x = image.img_to_array(img)

# Preprocess the image
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Make predictions
preds = model.predict(x)

# Print the predicted class
pred_class = decode_predictions(preds, top=1)[0][0][1]
print(f"There is {pred_class} in the image")

# Code By Nityam Upadhyay